---
- name: Create heimdall config volume
  community.docker.docker_volume:
    name: app_heimdall_config

- name: Ensure linuxserver/heimdall image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/heimdall
    source: pull
    force_source: yes
  register: pulled

- name: Remove heimdall container
  community.docker.docker_container:
    name: heimdall
    state: absent
  when: pulled.changed

- name: Get infos on heimdall container
  community.docker.docker_container_info:
    name: heimdall
  register: result

- name: Create heimdall container
  community.docker.docker_container:
    env:
     TZ: "{{app_heimdall_tz}}"
    image: lscr.io/linuxserver/heimdall
    mounts:
     - source: app_heimdall_config
       target: /config
    name: heimdall
    networks:
     - name: app-network
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
